<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.14"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>LCK Exception Handling: C++ Exception Handling</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">LCK Exception Handling
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.14 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">C++ Exception Handling </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><p>Exercising C++ exception handling.</p>
<p><a href="https://codingkata.tardate.com">:arrow_forward: return to the Catalog</a></p>
<h2>Notes</h2>
<p>The essentials of exception handling in c++:</p>
<ul>
<li>when compiling c++, exception handling is usually turned on by default. But this can be compiler-specific and require switches to enable</li>
<li>mulitple <code>catch</code> blocks allow catching different types of errors</li>
<li><a href="https://en.cppreference.com/w/cpp/language/noexcept_spec">noexcept specifier</a> indicates the method cannot throw an exception. Bad practice generally.<ul>
<li>noexcept is an improved version of <code>throw()</code>, which is deprecated in C++11</li>
</ul>
</li>
<li>polymorphism applies: must catch exception subclasses before ancestors</li>
</ul>
<h2>Demo</h2>
<p><a href="./exception_handling.cpp">exception_handling.cpp</a> runs through a variety of exception classes that are caught:</p>
<ul>
<li>simple ints</li>
<li>simple char messages</li>
<li>string messages</li>
<li>custom exception classes</li>
<li>polymorphic standard exceptions</li>
</ul>
<p>..and ends on an uncaught exception.</p>
<p>NB: this is updated for C++17 syntax - specifically the use of <code>noexcept</code> instead of <code>throw()</code>. </p><pre class="fragment">$ g++ -std=c++17 -o exception_handling.exe exception_handling.cpp &amp;&amp; ./exception_handling.exe

Testing a range of standard and custom exceptions..

Error code: 33
Basic error message: Oh deary me
String error message caught by reference: Out of bacon
bad_alloc error message caught by reference: std::bad_alloc
Generic exception error message caught by reference: std::exception
CustomException message caught by reference: Something bad happened

Now testing an exception in a constructor..

exception_handling.exe(28207,0x7fffae28f380) malloc: *** mach_vm_map(size=1000000000000000) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
bad_alloc message: std::bad_alloc

And we're still running!

But the next has no handler:

libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6
</pre><h2>Credits and References</h2>
<ul>
<li><a href="https://en.cppreference.com/w/cpp/language/noexcept_spec">noexcept specifier</a></li>
<li><a href="https://en.cppreference.com/w/cpp/language/except_spec">Dynamic exception specification</a></li>
<li><a href="http://www.cplusplus.com/doc/tutorial/exceptions/">exception tutorial</a> - cplusplus.com</li>
<li><a href="http://www.cplusplus.com/reference/exception/exception/">exception reference</a> - cplusplus.com</li>
<li><a href="https://www.udemy.com/learn-advanced-c-programming/">Learn Advanced C++ Programming</a></li>
<li><a href="https://codingkata.tardate.com/cpp/exception_handling/doc/html/">Doxygen documentation for the demo</a> </li>
</ul>
</div></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.14
</small></address>
</body>
</html>
